### ISSUE TITLE
add mock contacts when running on browser

### ISSUE THREAD

**Issue by GILREICH1** [LiraShapira/app#17]
### bug
Nothing is currently displayed on '/Send' page when running desktop on browser:

<img  src='https://github.com/LiraShapira/app/assets/78416008/273cc416-d7b2-4317-afbc-0ffea4b8e315' width=150 />

### Fix: 
- Add mock Contacts to mocks
- Set up else clause here: https://github.com/LiraShapira/app/blob/main/app/_layout.tsx#L54
- setContacts with mock list in else statement

**Comment by kurtmgray** [comment]
I'm happy to take this issue. Pretty closely related to  #20 .

**Comment by kurtmgray** [comment]
Thanks for assigning this to me. Which fields from the Contact type in expo-contacts should I prioritize in the mock? I can easily mock the primitive types; non-primitives will be a little bit more involved.

**Comment by GILREICH1** [comment]
Great thanks Kurt! I believe the properties we need to mock currently are:
```
{
   "firstName":"Aaron",
   "id":"821",
   "lastName":"Test",
   "name":"Aaron Test",
   "phoneNumbers": [
      {
         "id":"1345",
         "isPrimary":0,
         "label":"work",
         "number":"+447012345678",
      }
   ]
}
```
