### ISSUE TITLE
icon shading

### ISSUE THREAD

**Issue by GILREICH1** [LiraShapira/app#4]

**Comment by GILREICH1** [comment]
shading needs to be added to buttons in app to match wireframes

![Image](https://github.com/LiraShapira/app/assets/78416008/dc7b56fa-6c78-4cd1-a1c1-408a0b852e13)


[wireframe](https://www.figma.com/file/bbWVhIyCiNv6YpzvnNmj6F/%D7%9E%D7%A6%D7%92%D7%AA-%D7%92%D7%9E%D7%A8-%D7%9C%D7%99%D7%A8%D7%94-%D7%A9%D7%A4%D7%99%D7%A8%D7%90?type=design&node-id=10-1577&mode=design&t=HVABu3ntQMxPEubm-0)

**Comment by rsimcha** [comment]
@GILREICH1 I see that the icons are shaded already no?
